name: flutter_secure_keyboard
description: Mobile secure keyboard to prevent KeyLogger attack and screen capture.
version: 2.1.2
author: WOO JIN HWANG <hwj930513@naver.com>
homepage: https://github.com/Dev-hwang/flutter_secure_keyboard

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.flutter_secure_keyboard
        pluginClass: FlutterSecureKeyboardPlugin
      ios:
        pluginClass: FlutterSecureKeyboardPlugin
